add_rules("mode.debug", "mode.release", "mode.profile")

add_requires("libaccel-config", {system = true})
add_requires("fmt", {system = true})
add_requires("stdexec", {system = true})
add_requires("cpptrace", {system = true})

set_languages("c++23")

add_includedirs("include", "src")


add_syslinks("stdc++exp")

target("dsa-stdexec")
    set_kind("binary")
    add_files("src/**.cpp")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    -- add_packages("proxy")
    add_cflags("-menqcmd")
    add_cxxflags("-menqcmd")
    add_cflags("-movdir64b")
    add_cxxflags("-mmovdir64b")
    after_build(function (target)
        os.exec("sudo setcap cap_sys_rawio+ep " .. target:targetdir() .. "/dsa-stdexec")
    end)


target("polling_loop_test")
    set_kind("binary")
    add_files("test/polling_loop_test.cpp")
    add_packages("stdexec")
    add_packages("fmt")

target("dsa-benchmark")
    set_kind("binary")
    set_default(false)
    add_files("src/main.cpp", "src/dsa/dsa.cpp")
    add_packages("libaccel-config")
    add_packages("fmt")
    add_packages("stdexec")
    -- add_packages("proxy")
    add_packages("cpptrace")
    add_cflags("-menqcmd", "-movdir64b")
    add_cxxflags("-menqcmd", "-mmovdir64b")
    after_build(function (target)
        os.exec("sudo setcap cap_sys_rawio+ep " .. target:targetdir() .. "/dsa-benchmark")
    end)
